language: javascript
node_js:
 - "14"
env:
 - NODE_ENV=ci
dist: trusty
services:
  - docker
cache:
 directories:
  - node_modules
  - client/node_modules
install:
 - npm ci
script:
 - npm run build
 - npm run test
 - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 - docker build -t balrrazh/balraj-repository1 .
 - docker push balrrazh/balraj-repository1:latest
 - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
deploy:
 provider: heroku
 api_key:
  secure: c72746a4-15f1-4c34-9732-6f4066d88e5a
 app: angular-ui-app # app name on heroku which am deploying to.