language: javascript
node_js:
- '14'
env:
- NODE_ENV=ci
dist: trusty
services:
- docker
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm ci
script:
- npm run build
- npm run test
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t balrajhanmanthugari/angular-ui:v1 .
- docker push balrajhanmanthugari/angular-ui:v1
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: mXr2n/lRw1fszdgJiKQgiiNZqFgLrD60UzVVGsSJp6hBK9wR56nfSqKIN2s62nSVS2QyWUm2qNKW1K5BCzbMy6WRxhROiaYyGIemURCiWnDej26llshds1fzIlkd/4XXx8y9JOvGizc+Wp0bTpg8rydg12h9RbN8fG7t1cHAa5mYewdqg29y2THHkdZRKMoSze307W4nDBVRFbnK002XPaCk9NaVRGpBECIXp0tZrZtTomkq6njZJw5/AkexhWfXK/3tKdp9Td0uGDORyAIJfHm6rdAxaXp9SpHoud9+9FTlni2rB7EbexwmKNNMT0S9QSn1k20zxoMfsLW8Xabtayu/Bc6rkhUb1ZIT1rBdL7CilouzR9WtNR91LPma4eqqDKkOdyB100KSEvbwkT0JTTrquJG3CvF4BA0heMou130iIt0X5aRuytwBazjiP87FDLvJMg8OImHb8QPDSZfCXk3bSUbapsDxLE9fsxxwjVog0M0JltMAiicitjJ6eyOivIiMXUtSAqJP0Y4FVmQxoBo/oPsuIEQCCpU9SJGhgmWQTovNTs0HkD8aB6D+POSS8h86ABecF1m5Var0xD3crYCdiHORPO9f5dmERtID6bA84X1Q5JsOt9SZLYLaayLQ4WKwvPnLjkL7WD+mpwihZzO/49IFRg6xKxb2lOSn0Z0=
  app: angular-ui-app
