language: javascript
node_js:
  - "14"
env:
  - NODE_ENV=ci
dist: dist
services:
  - docker
cache:
  directories:
    - node_modules
install:
  - npm ci
script:
  - npm run build:prod
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t balrajhanmanthugari/angular-ui:v2 .
  - docker push balrajhanmanthugari/angular-ui:v2
