language: javascript
node_js:
  - '14'
env:
  - NODE_ENV=ci
dist: trusty
services:
  - docker
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm ci
script:
  - npm run build
  - npm run test
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t balrrazh/balraj-repository1:v1 .
  - docker push balrrazh/balraj-repository1:v1
