language: javascript
node_js:
 - "14"
env:
 - NODE_ENV=ci
dist: trusty
cache:
 directories:
  - node_modules
  - client/node_modules
install:
 - npm ci
script:
 - npm run lint
 - npm run build
 - npm run test
