language: javascript
node_js:
 - "14"
env:
 - NODE_ENV=ci
 - HEROKU_API_KEY=c72746a4-15f1-4c34-9732-6f4066d88e5a
 - HEROKU_APP_NAME=angular-ui-app
dist: trusty
services:
  - docker
cache:
 directories:
  - node_modules
  - client/node_modules
install:
 - npm ci
script:
 - npm run build
 - npm run test
 - docker build -t angular-ui-image .
after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh